/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package garbagemanagent;

/**
 *
 * @author Asus
 */
public class recycle_plans extends javax.swing.JInternalFrame {

    /**
     * Creates new form recycle_plans
     */
    public recycle_plans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paper = new javax.swing.JLabel();
        plastic2 = new javax.swing.JLabel();
        metal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setClosable(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myImages/recycle.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("                                   RECYCLING PLANS ");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        paper.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        paper.setText("Paper Recycling Plant Business Plan");
        paper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paperMouseClicked(evt);
            }
        });

        plastic2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        plastic2.setText("Plastic Recycling Business Plan");
        plastic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plastic2MouseClicked(evt);
            }
        });

        metal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        metal.setText("Apex Recycling (Scrap Metal Recycling) Business Plan");
        metal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metalMouseClicked(evt);
            }
        });

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paper)
                            .addComponent(plastic2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(paper)
                .addGap(18, 18, 18)
                .addComponent(plastic2)
                .addGap(18, 18, 18)
                .addComponent(metal)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 788, 462);
    }// </editor-fold>//GEN-END:initComponents

    private void paperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paperMouseClicked
        area.setText("This business plan shows a comprehensive process to recycle paper.\nIt explains ways of earning quick profits from used paper \nand how recycling this material can fulfill the quickly growing demand for paper products.");

    }//GEN-LAST:event_paperMouseClicked

    private void plastic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plastic2MouseClicked
        area.setText("This business plan identifies things that went wrong in the initial\n launching of Scottish Recycling Company to recycle used coffee cups, soft drink bottles,\n shrink wrap, bread bags, cling film, car bumpers, food packaging, milk bottles, cooking oil containers and other material.\n" +
"\n" +
"It also shows a complete roadmap to overcome the previous problems along\n with strategies to succeed in the re-launching.");

    }//GEN-LAST:event_plastic2MouseClicked

    private void metalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metalMouseClicked
        area.setText("The business plan of Apex Recycling illustrates the scenario for creating \na world-class metal shredding facility which is capable of producing \nrecycled products from scrap metals.");
        
        

    }//GEN-LAST:event_metalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel metal;
    private javax.swing.JLabel paper;
    private javax.swing.JLabel plastic2;
    // End of variables declaration//GEN-END:variables
}
